// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: record.proto

package com.bh.spider.consistent.raft.wal.pb;

public interface SnapshotOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.bh.spider.consistent.raft.wal.pb.Snapshot)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 index = 1;</code>
   */
  long getIndex();

  /**
   * <code>uint64 term = 2;</code>
   */
  long getTerm();
}
