// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: raft.proto

package com.bh.spider.consistent.raft.pb;

/**
 * Protobuf type {@code com.bh.spider.consistent.raft.pb.ConfChange}
 */
public  final class ConfChange extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.bh.spider.consistent.raft.pb.ConfChange)
    ConfChangeOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ConfChange.newBuilder() to construct.
  private ConfChange(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ConfChange() {
    type_ = 0;
    context_ = com.google.protobuf.ByteString.EMPTY;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ConfChange(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            iD_ = input.readUInt64();
            break;
          }
          case 16: {
            int rawValue = input.readEnum();

            type_ = rawValue;
            break;
          }
          case 24: {

            nodeID_ = input.readUInt64();
            break;
          }
          case 34: {

            context_ = input.readBytes();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.bh.spider.consistent.raft.pb.RaftProto.internal_static_com_bh_spider_consistent_raft_pb_ConfChange_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.bh.spider.consistent.raft.pb.RaftProto.internal_static_com_bh_spider_consistent_raft_pb_ConfChange_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.bh.spider.consistent.raft.pb.ConfChange.class, com.bh.spider.consistent.raft.pb.ConfChange.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private long iD_;
  /**
   * <code>uint64 ID = 1;</code>
   */
  public long getID() {
    return iD_;
  }

  public static final int TYPE_FIELD_NUMBER = 2;
  private int type_;
  /**
   * <code>.com.bh.spider.consistent.raft.pb.ConfChangeType Type = 2;</code>
   */
  public int getTypeValue() {
    return type_;
  }
  /**
   * <code>.com.bh.spider.consistent.raft.pb.ConfChangeType Type = 2;</code>
   */
  public com.bh.spider.consistent.raft.pb.ConfChangeType getType() {
    @SuppressWarnings("deprecation")
    com.bh.spider.consistent.raft.pb.ConfChangeType result = com.bh.spider.consistent.raft.pb.ConfChangeType.valueOf(type_);
    return result == null ? com.bh.spider.consistent.raft.pb.ConfChangeType.UNRECOGNIZED : result;
  }

  public static final int NODEID_FIELD_NUMBER = 3;
  private long nodeID_;
  /**
   * <code>uint64 NodeID = 3;</code>
   */
  public long getNodeID() {
    return nodeID_;
  }

  public static final int CONTEXT_FIELD_NUMBER = 4;
  private com.google.protobuf.ByteString context_;
  /**
   * <code>bytes Context = 4;</code>
   */
  public com.google.protobuf.ByteString getContext() {
    return context_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (iD_ != 0L) {
      output.writeUInt64(1, iD_);
    }
    if (type_ != com.bh.spider.consistent.raft.pb.ConfChangeType.ConfChangeAddNode.getNumber()) {
      output.writeEnum(2, type_);
    }
    if (nodeID_ != 0L) {
      output.writeUInt64(3, nodeID_);
    }
    if (!context_.isEmpty()) {
      output.writeBytes(4, context_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (iD_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(1, iD_);
    }
    if (type_ != com.bh.spider.consistent.raft.pb.ConfChangeType.ConfChangeAddNode.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, type_);
    }
    if (nodeID_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(3, nodeID_);
    }
    if (!context_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(4, context_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.bh.spider.consistent.raft.pb.ConfChange)) {
      return super.equals(obj);
    }
    com.bh.spider.consistent.raft.pb.ConfChange other = (com.bh.spider.consistent.raft.pb.ConfChange) obj;

    if (getID()
        != other.getID()) return false;
    if (type_ != other.type_) return false;
    if (getNodeID()
        != other.getNodeID()) return false;
    if (!getContext()
        .equals(other.getContext())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getID());
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + type_;
    hash = (37 * hash) + NODEID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getNodeID());
    hash = (37 * hash) + CONTEXT_FIELD_NUMBER;
    hash = (53 * hash) + getContext().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.bh.spider.consistent.raft.pb.ConfChange parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bh.spider.consistent.raft.pb.ConfChange parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bh.spider.consistent.raft.pb.ConfChange parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bh.spider.consistent.raft.pb.ConfChange parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bh.spider.consistent.raft.pb.ConfChange parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bh.spider.consistent.raft.pb.ConfChange parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bh.spider.consistent.raft.pb.ConfChange parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.bh.spider.consistent.raft.pb.ConfChange parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.bh.spider.consistent.raft.pb.ConfChange parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.bh.spider.consistent.raft.pb.ConfChange parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.bh.spider.consistent.raft.pb.ConfChange parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.bh.spider.consistent.raft.pb.ConfChange parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.bh.spider.consistent.raft.pb.ConfChange prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.bh.spider.consistent.raft.pb.ConfChange}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.bh.spider.consistent.raft.pb.ConfChange)
      com.bh.spider.consistent.raft.pb.ConfChangeOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bh.spider.consistent.raft.pb.RaftProto.internal_static_com_bh_spider_consistent_raft_pb_ConfChange_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bh.spider.consistent.raft.pb.RaftProto.internal_static_com_bh_spider_consistent_raft_pb_ConfChange_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bh.spider.consistent.raft.pb.ConfChange.class, com.bh.spider.consistent.raft.pb.ConfChange.Builder.class);
    }

    // Construct using com.bh.spider.consistent.raft.pb.ConfChange.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      iD_ = 0L;

      type_ = 0;

      nodeID_ = 0L;

      context_ = com.google.protobuf.ByteString.EMPTY;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.bh.spider.consistent.raft.pb.RaftProto.internal_static_com_bh_spider_consistent_raft_pb_ConfChange_descriptor;
    }

    @java.lang.Override
    public com.bh.spider.consistent.raft.pb.ConfChange getDefaultInstanceForType() {
      return com.bh.spider.consistent.raft.pb.ConfChange.getDefaultInstance();
    }

    @java.lang.Override
    public com.bh.spider.consistent.raft.pb.ConfChange build() {
      com.bh.spider.consistent.raft.pb.ConfChange result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.bh.spider.consistent.raft.pb.ConfChange buildPartial() {
      com.bh.spider.consistent.raft.pb.ConfChange result = new com.bh.spider.consistent.raft.pb.ConfChange(this);
      result.iD_ = iD_;
      result.type_ = type_;
      result.nodeID_ = nodeID_;
      result.context_ = context_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.bh.spider.consistent.raft.pb.ConfChange) {
        return mergeFrom((com.bh.spider.consistent.raft.pb.ConfChange)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.bh.spider.consistent.raft.pb.ConfChange other) {
      if (other == com.bh.spider.consistent.raft.pb.ConfChange.getDefaultInstance()) return this;
      if (other.getID() != 0L) {
        setID(other.getID());
      }
      if (other.type_ != 0) {
        setTypeValue(other.getTypeValue());
      }
      if (other.getNodeID() != 0L) {
        setNodeID(other.getNodeID());
      }
      if (other.getContext() != com.google.protobuf.ByteString.EMPTY) {
        setContext(other.getContext());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.bh.spider.consistent.raft.pb.ConfChange parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.bh.spider.consistent.raft.pb.ConfChange) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long iD_ ;
    /**
     * <code>uint64 ID = 1;</code>
     */
    public long getID() {
      return iD_;
    }
    /**
     * <code>uint64 ID = 1;</code>
     */
    public Builder setID(long value) {
      
      iD_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 ID = 1;</code>
     */
    public Builder clearID() {
      
      iD_ = 0L;
      onChanged();
      return this;
    }

    private int type_ = 0;
    /**
     * <code>.com.bh.spider.consistent.raft.pb.ConfChangeType Type = 2;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.com.bh.spider.consistent.raft.pb.ConfChangeType Type = 2;</code>
     */
    public Builder setTypeValue(int value) {
      type_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.com.bh.spider.consistent.raft.pb.ConfChangeType Type = 2;</code>
     */
    public com.bh.spider.consistent.raft.pb.ConfChangeType getType() {
      @SuppressWarnings("deprecation")
      com.bh.spider.consistent.raft.pb.ConfChangeType result = com.bh.spider.consistent.raft.pb.ConfChangeType.valueOf(type_);
      return result == null ? com.bh.spider.consistent.raft.pb.ConfChangeType.UNRECOGNIZED : result;
    }
    /**
     * <code>.com.bh.spider.consistent.raft.pb.ConfChangeType Type = 2;</code>
     */
    public Builder setType(com.bh.spider.consistent.raft.pb.ConfChangeType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      type_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.com.bh.spider.consistent.raft.pb.ConfChangeType Type = 2;</code>
     */
    public Builder clearType() {
      
      type_ = 0;
      onChanged();
      return this;
    }

    private long nodeID_ ;
    /**
     * <code>uint64 NodeID = 3;</code>
     */
    public long getNodeID() {
      return nodeID_;
    }
    /**
     * <code>uint64 NodeID = 3;</code>
     */
    public Builder setNodeID(long value) {
      
      nodeID_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 NodeID = 3;</code>
     */
    public Builder clearNodeID() {
      
      nodeID_ = 0L;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString context_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes Context = 4;</code>
     */
    public com.google.protobuf.ByteString getContext() {
      return context_;
    }
    /**
     * <code>bytes Context = 4;</code>
     */
    public Builder setContext(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      context_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes Context = 4;</code>
     */
    public Builder clearContext() {
      
      context_ = getDefaultInstance().getContext();
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.bh.spider.consistent.raft.pb.ConfChange)
  }

  // @@protoc_insertion_point(class_scope:com.bh.spider.consistent.raft.pb.ConfChange)
  private static final com.bh.spider.consistent.raft.pb.ConfChange DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.bh.spider.consistent.raft.pb.ConfChange();
  }

  public static com.bh.spider.consistent.raft.pb.ConfChange getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ConfChange>
      PARSER = new com.google.protobuf.AbstractParser<ConfChange>() {
    @java.lang.Override
    public ConfChange parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ConfChange(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ConfChange> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ConfChange> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.bh.spider.consistent.raft.pb.ConfChange getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

