// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: raft.proto

package com.bh.spider.consistent.raft.pb;

public interface ConfStateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.bh.spider.consistent.raft.pb.ConfState)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated uint64 nodes = 1;</code>
   */
  java.util.List<java.lang.Long> getNodesList();
  /**
   * <code>repeated uint64 nodes = 1;</code>
   */
  int getNodesCount();
  /**
   * <code>repeated uint64 nodes = 1;</code>
   */
  long getNodes(int index);

  /**
   * <code>repeated uint64 learners = 2;</code>
   */
  java.util.List<java.lang.Long> getLearnersList();
  /**
   * <code>repeated uint64 learners = 2;</code>
   */
  int getLearnersCount();
  /**
   * <code>repeated uint64 learners = 2;</code>
   */
  long getLearners(int index);
}
