// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: raft.proto

package com.bh.spider.consistent.raft.pb;

/**
 * Protobuf type {@code com.bh.spider.consistent.raft.pb.ConfState}
 */
public  final class ConfState extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.bh.spider.consistent.raft.pb.ConfState)
    ConfStateOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ConfState.newBuilder() to construct.
  private ConfState(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ConfState() {
    nodes_ = emptyLongList();
    learners_ = emptyLongList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ConfState(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              nodes_ = newLongList();
              mutable_bitField0_ |= 0x00000001;
            }
            nodes_.addLong(input.readUInt64());
            break;
          }
          case 10: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000001) != 0) && input.getBytesUntilLimit() > 0) {
              nodes_ = newLongList();
              mutable_bitField0_ |= 0x00000001;
            }
            while (input.getBytesUntilLimit() > 0) {
              nodes_.addLong(input.readUInt64());
            }
            input.popLimit(limit);
            break;
          }
          case 16: {
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              learners_ = newLongList();
              mutable_bitField0_ |= 0x00000002;
            }
            learners_.addLong(input.readUInt64());
            break;
          }
          case 18: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000002) != 0) && input.getBytesUntilLimit() > 0) {
              learners_ = newLongList();
              mutable_bitField0_ |= 0x00000002;
            }
            while (input.getBytesUntilLimit() > 0) {
              learners_.addLong(input.readUInt64());
            }
            input.popLimit(limit);
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        nodes_.makeImmutable(); // C
      }
      if (((mutable_bitField0_ & 0x00000002) != 0)) {
        learners_.makeImmutable(); // C
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.bh.spider.consistent.raft.pb.RaftProto.internal_static_com_bh_spider_consistent_raft_pb_ConfState_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.bh.spider.consistent.raft.pb.RaftProto.internal_static_com_bh_spider_consistent_raft_pb_ConfState_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.bh.spider.consistent.raft.pb.ConfState.class, com.bh.spider.consistent.raft.pb.ConfState.Builder.class);
  }

  public static final int NODES_FIELD_NUMBER = 1;
  private com.google.protobuf.Internal.LongList nodes_;
  /**
   * <code>repeated uint64 nodes = 1;</code>
   */
  public java.util.List<java.lang.Long>
      getNodesList() {
    return nodes_;
  }
  /**
   * <code>repeated uint64 nodes = 1;</code>
   */
  public int getNodesCount() {
    return nodes_.size();
  }
  /**
   * <code>repeated uint64 nodes = 1;</code>
   */
  public long getNodes(int index) {
    return nodes_.getLong(index);
  }
  private int nodesMemoizedSerializedSize = -1;

  public static final int LEARNERS_FIELD_NUMBER = 2;
  private com.google.protobuf.Internal.LongList learners_;
  /**
   * <code>repeated uint64 learners = 2;</code>
   */
  public java.util.List<java.lang.Long>
      getLearnersList() {
    return learners_;
  }
  /**
   * <code>repeated uint64 learners = 2;</code>
   */
  public int getLearnersCount() {
    return learners_.size();
  }
  /**
   * <code>repeated uint64 learners = 2;</code>
   */
  public long getLearners(int index) {
    return learners_.getLong(index);
  }
  private int learnersMemoizedSerializedSize = -1;

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (getNodesList().size() > 0) {
      output.writeUInt32NoTag(10);
      output.writeUInt32NoTag(nodesMemoizedSerializedSize);
    }
    for (int i = 0; i < nodes_.size(); i++) {
      output.writeUInt64NoTag(nodes_.getLong(i));
    }
    if (getLearnersList().size() > 0) {
      output.writeUInt32NoTag(18);
      output.writeUInt32NoTag(learnersMemoizedSerializedSize);
    }
    for (int i = 0; i < learners_.size(); i++) {
      output.writeUInt64NoTag(learners_.getLong(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < nodes_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeUInt64SizeNoTag(nodes_.getLong(i));
      }
      size += dataSize;
      if (!getNodesList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      nodesMemoizedSerializedSize = dataSize;
    }
    {
      int dataSize = 0;
      for (int i = 0; i < learners_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeUInt64SizeNoTag(learners_.getLong(i));
      }
      size += dataSize;
      if (!getLearnersList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      learnersMemoizedSerializedSize = dataSize;
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.bh.spider.consistent.raft.pb.ConfState)) {
      return super.equals(obj);
    }
    com.bh.spider.consistent.raft.pb.ConfState other = (com.bh.spider.consistent.raft.pb.ConfState) obj;

    if (!getNodesList()
        .equals(other.getNodesList())) return false;
    if (!getLearnersList()
        .equals(other.getLearnersList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getNodesCount() > 0) {
      hash = (37 * hash) + NODES_FIELD_NUMBER;
      hash = (53 * hash) + getNodesList().hashCode();
    }
    if (getLearnersCount() > 0) {
      hash = (37 * hash) + LEARNERS_FIELD_NUMBER;
      hash = (53 * hash) + getLearnersList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.bh.spider.consistent.raft.pb.ConfState parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bh.spider.consistent.raft.pb.ConfState parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bh.spider.consistent.raft.pb.ConfState parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bh.spider.consistent.raft.pb.ConfState parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bh.spider.consistent.raft.pb.ConfState parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bh.spider.consistent.raft.pb.ConfState parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bh.spider.consistent.raft.pb.ConfState parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.bh.spider.consistent.raft.pb.ConfState parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.bh.spider.consistent.raft.pb.ConfState parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.bh.spider.consistent.raft.pb.ConfState parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.bh.spider.consistent.raft.pb.ConfState parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.bh.spider.consistent.raft.pb.ConfState parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.bh.spider.consistent.raft.pb.ConfState prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.bh.spider.consistent.raft.pb.ConfState}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.bh.spider.consistent.raft.pb.ConfState)
      com.bh.spider.consistent.raft.pb.ConfStateOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bh.spider.consistent.raft.pb.RaftProto.internal_static_com_bh_spider_consistent_raft_pb_ConfState_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bh.spider.consistent.raft.pb.RaftProto.internal_static_com_bh_spider_consistent_raft_pb_ConfState_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bh.spider.consistent.raft.pb.ConfState.class, com.bh.spider.consistent.raft.pb.ConfState.Builder.class);
    }

    // Construct using com.bh.spider.consistent.raft.pb.ConfState.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      nodes_ = emptyLongList();
      bitField0_ = (bitField0_ & ~0x00000001);
      learners_ = emptyLongList();
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.bh.spider.consistent.raft.pb.RaftProto.internal_static_com_bh_spider_consistent_raft_pb_ConfState_descriptor;
    }

    @java.lang.Override
    public com.bh.spider.consistent.raft.pb.ConfState getDefaultInstanceForType() {
      return com.bh.spider.consistent.raft.pb.ConfState.getDefaultInstance();
    }

    @java.lang.Override
    public com.bh.spider.consistent.raft.pb.ConfState build() {
      com.bh.spider.consistent.raft.pb.ConfState result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.bh.spider.consistent.raft.pb.ConfState buildPartial() {
      com.bh.spider.consistent.raft.pb.ConfState result = new com.bh.spider.consistent.raft.pb.ConfState(this);
      int from_bitField0_ = bitField0_;
      if (((bitField0_ & 0x00000001) != 0)) {
        nodes_.makeImmutable();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.nodes_ = nodes_;
      if (((bitField0_ & 0x00000002) != 0)) {
        learners_.makeImmutable();
        bitField0_ = (bitField0_ & ~0x00000002);
      }
      result.learners_ = learners_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.bh.spider.consistent.raft.pb.ConfState) {
        return mergeFrom((com.bh.spider.consistent.raft.pb.ConfState)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.bh.spider.consistent.raft.pb.ConfState other) {
      if (other == com.bh.spider.consistent.raft.pb.ConfState.getDefaultInstance()) return this;
      if (!other.nodes_.isEmpty()) {
        if (nodes_.isEmpty()) {
          nodes_ = other.nodes_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureNodesIsMutable();
          nodes_.addAll(other.nodes_);
        }
        onChanged();
      }
      if (!other.learners_.isEmpty()) {
        if (learners_.isEmpty()) {
          learners_ = other.learners_;
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          ensureLearnersIsMutable();
          learners_.addAll(other.learners_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.bh.spider.consistent.raft.pb.ConfState parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.bh.spider.consistent.raft.pb.ConfState) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.Internal.LongList nodes_ = emptyLongList();
    private void ensureNodesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        nodes_ = mutableCopy(nodes_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated uint64 nodes = 1;</code>
     */
    public java.util.List<java.lang.Long>
        getNodesList() {
      return ((bitField0_ & 0x00000001) != 0) ?
               java.util.Collections.unmodifiableList(nodes_) : nodes_;
    }
    /**
     * <code>repeated uint64 nodes = 1;</code>
     */
    public int getNodesCount() {
      return nodes_.size();
    }
    /**
     * <code>repeated uint64 nodes = 1;</code>
     */
    public long getNodes(int index) {
      return nodes_.getLong(index);
    }
    /**
     * <code>repeated uint64 nodes = 1;</code>
     */
    public Builder setNodes(
        int index, long value) {
      ensureNodesIsMutable();
      nodes_.setLong(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated uint64 nodes = 1;</code>
     */
    public Builder addNodes(long value) {
      ensureNodesIsMutable();
      nodes_.addLong(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated uint64 nodes = 1;</code>
     */
    public Builder addAllNodes(
        java.lang.Iterable<? extends java.lang.Long> values) {
      ensureNodesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, nodes_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated uint64 nodes = 1;</code>
     */
    public Builder clearNodes() {
      nodes_ = emptyLongList();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }

    private com.google.protobuf.Internal.LongList learners_ = emptyLongList();
    private void ensureLearnersIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        learners_ = mutableCopy(learners_);
        bitField0_ |= 0x00000002;
       }
    }
    /**
     * <code>repeated uint64 learners = 2;</code>
     */
    public java.util.List<java.lang.Long>
        getLearnersList() {
      return ((bitField0_ & 0x00000002) != 0) ?
               java.util.Collections.unmodifiableList(learners_) : learners_;
    }
    /**
     * <code>repeated uint64 learners = 2;</code>
     */
    public int getLearnersCount() {
      return learners_.size();
    }
    /**
     * <code>repeated uint64 learners = 2;</code>
     */
    public long getLearners(int index) {
      return learners_.getLong(index);
    }
    /**
     * <code>repeated uint64 learners = 2;</code>
     */
    public Builder setLearners(
        int index, long value) {
      ensureLearnersIsMutable();
      learners_.setLong(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated uint64 learners = 2;</code>
     */
    public Builder addLearners(long value) {
      ensureLearnersIsMutable();
      learners_.addLong(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated uint64 learners = 2;</code>
     */
    public Builder addAllLearners(
        java.lang.Iterable<? extends java.lang.Long> values) {
      ensureLearnersIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, learners_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated uint64 learners = 2;</code>
     */
    public Builder clearLearners() {
      learners_ = emptyLongList();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.bh.spider.consistent.raft.pb.ConfState)
  }

  // @@protoc_insertion_point(class_scope:com.bh.spider.consistent.raft.pb.ConfState)
  private static final com.bh.spider.consistent.raft.pb.ConfState DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.bh.spider.consistent.raft.pb.ConfState();
  }

  public static com.bh.spider.consistent.raft.pb.ConfState getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ConfState>
      PARSER = new com.google.protobuf.AbstractParser<ConfState>() {
    @java.lang.Override
    public ConfState parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ConfState(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ConfState> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ConfState> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.bh.spider.consistent.raft.pb.ConfState getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

