// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: raft.proto

package com.bh.spider.consistent.raft.pb;

public interface ConfChangeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.bh.spider.consistent.raft.pb.ConfChange)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 ID = 1;</code>
   */
  long getID();

  /**
   * <code>.com.bh.spider.consistent.raft.pb.ConfChangeType Type = 2;</code>
   */
  int getTypeValue();
  /**
   * <code>.com.bh.spider.consistent.raft.pb.ConfChangeType Type = 2;</code>
   */
  com.bh.spider.consistent.raft.pb.ConfChangeType getType();

  /**
   * <code>uint64 NodeID = 3;</code>
   */
  long getNodeID();

  /**
   * <code>bytes Context = 4;</code>
   */
  com.google.protobuf.ByteString getContext();
}
