// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: raft.proto

package com.bh.spider.consistent.raft.pb;

public interface EntryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.bh.spider.consistent.raft.pb.Entry)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * must be 64-bit aligned for atomic operations
   * </pre>
   *
   * <code>uint64 Term = 2;</code>
   */
  long getTerm();

  /**
   * <pre>
   * must be 64-bit aligned for atomic operations
   * </pre>
   *
   * <code>uint64 Index = 3;</code>
   */
  long getIndex();

  /**
   * <code>.com.bh.spider.consistent.raft.pb.EntryType Type = 1;</code>
   */
  int getTypeValue();
  /**
   * <code>.com.bh.spider.consistent.raft.pb.EntryType Type = 1;</code>
   */
  com.bh.spider.consistent.raft.pb.EntryType getType();

  /**
   * <code>bytes Data = 4;</code>
   */
  com.google.protobuf.ByteString getData();
}
