// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: raft.proto

package com.bh.spider.consistent.raft.pb;

/**
 * Protobuf type {@code com.bh.spider.consistent.raft.pb.Entry}
 */
public  final class Entry extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.bh.spider.consistent.raft.pb.Entry)
    EntryOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Entry.newBuilder() to construct.
  private Entry(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Entry() {
    type_ = 0;
    data_ = com.google.protobuf.ByteString.EMPTY;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Entry(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();

            type_ = rawValue;
            break;
          }
          case 16: {

            term_ = input.readUInt64();
            break;
          }
          case 24: {

            index_ = input.readUInt64();
            break;
          }
          case 34: {

            data_ = input.readBytes();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.bh.spider.consistent.raft.pb.RaftProto.internal_static_com_bh_spider_consistent_raft_pb_Entry_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.bh.spider.consistent.raft.pb.RaftProto.internal_static_com_bh_spider_consistent_raft_pb_Entry_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.bh.spider.consistent.raft.pb.Entry.class, com.bh.spider.consistent.raft.pb.Entry.Builder.class);
  }

  public static final int TERM_FIELD_NUMBER = 2;
  private long term_;
  /**
   * <pre>
   * must be 64-bit aligned for atomic operations
   * </pre>
   *
   * <code>uint64 Term = 2;</code>
   */
  public long getTerm() {
    return term_;
  }

  public static final int INDEX_FIELD_NUMBER = 3;
  private long index_;
  /**
   * <pre>
   * must be 64-bit aligned for atomic operations
   * </pre>
   *
   * <code>uint64 Index = 3;</code>
   */
  public long getIndex() {
    return index_;
  }

  public static final int TYPE_FIELD_NUMBER = 1;
  private int type_;
  /**
   * <code>.com.bh.spider.consistent.raft.pb.EntryType Type = 1;</code>
   */
  public int getTypeValue() {
    return type_;
  }
  /**
   * <code>.com.bh.spider.consistent.raft.pb.EntryType Type = 1;</code>
   */
  public com.bh.spider.consistent.raft.pb.EntryType getType() {
    @SuppressWarnings("deprecation")
    com.bh.spider.consistent.raft.pb.EntryType result = com.bh.spider.consistent.raft.pb.EntryType.valueOf(type_);
    return result == null ? com.bh.spider.consistent.raft.pb.EntryType.UNRECOGNIZED : result;
  }

  public static final int DATA_FIELD_NUMBER = 4;
  private com.google.protobuf.ByteString data_;
  /**
   * <code>bytes Data = 4;</code>
   */
  public com.google.protobuf.ByteString getData() {
    return data_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (type_ != com.bh.spider.consistent.raft.pb.EntryType.EntryNormal.getNumber()) {
      output.writeEnum(1, type_);
    }
    if (term_ != 0L) {
      output.writeUInt64(2, term_);
    }
    if (index_ != 0L) {
      output.writeUInt64(3, index_);
    }
    if (!data_.isEmpty()) {
      output.writeBytes(4, data_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (type_ != com.bh.spider.consistent.raft.pb.EntryType.EntryNormal.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, type_);
    }
    if (term_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(2, term_);
    }
    if (index_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(3, index_);
    }
    if (!data_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(4, data_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.bh.spider.consistent.raft.pb.Entry)) {
      return super.equals(obj);
    }
    com.bh.spider.consistent.raft.pb.Entry other = (com.bh.spider.consistent.raft.pb.Entry) obj;

    if (getTerm()
        != other.getTerm()) return false;
    if (getIndex()
        != other.getIndex()) return false;
    if (type_ != other.type_) return false;
    if (!getData()
        .equals(other.getData())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TERM_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTerm());
    hash = (37 * hash) + INDEX_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getIndex());
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + type_;
    hash = (37 * hash) + DATA_FIELD_NUMBER;
    hash = (53 * hash) + getData().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.bh.spider.consistent.raft.pb.Entry parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bh.spider.consistent.raft.pb.Entry parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bh.spider.consistent.raft.pb.Entry parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bh.spider.consistent.raft.pb.Entry parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bh.spider.consistent.raft.pb.Entry parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bh.spider.consistent.raft.pb.Entry parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bh.spider.consistent.raft.pb.Entry parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.bh.spider.consistent.raft.pb.Entry parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.bh.spider.consistent.raft.pb.Entry parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.bh.spider.consistent.raft.pb.Entry parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.bh.spider.consistent.raft.pb.Entry parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.bh.spider.consistent.raft.pb.Entry parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.bh.spider.consistent.raft.pb.Entry prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.bh.spider.consistent.raft.pb.Entry}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.bh.spider.consistent.raft.pb.Entry)
      com.bh.spider.consistent.raft.pb.EntryOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bh.spider.consistent.raft.pb.RaftProto.internal_static_com_bh_spider_consistent_raft_pb_Entry_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bh.spider.consistent.raft.pb.RaftProto.internal_static_com_bh_spider_consistent_raft_pb_Entry_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bh.spider.consistent.raft.pb.Entry.class, com.bh.spider.consistent.raft.pb.Entry.Builder.class);
    }

    // Construct using com.bh.spider.consistent.raft.pb.Entry.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      term_ = 0L;

      index_ = 0L;

      type_ = 0;

      data_ = com.google.protobuf.ByteString.EMPTY;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.bh.spider.consistent.raft.pb.RaftProto.internal_static_com_bh_spider_consistent_raft_pb_Entry_descriptor;
    }

    @java.lang.Override
    public com.bh.spider.consistent.raft.pb.Entry getDefaultInstanceForType() {
      return com.bh.spider.consistent.raft.pb.Entry.getDefaultInstance();
    }

    @java.lang.Override
    public com.bh.spider.consistent.raft.pb.Entry build() {
      com.bh.spider.consistent.raft.pb.Entry result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.bh.spider.consistent.raft.pb.Entry buildPartial() {
      com.bh.spider.consistent.raft.pb.Entry result = new com.bh.spider.consistent.raft.pb.Entry(this);
      result.term_ = term_;
      result.index_ = index_;
      result.type_ = type_;
      result.data_ = data_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.bh.spider.consistent.raft.pb.Entry) {
        return mergeFrom((com.bh.spider.consistent.raft.pb.Entry)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.bh.spider.consistent.raft.pb.Entry other) {
      if (other == com.bh.spider.consistent.raft.pb.Entry.getDefaultInstance()) return this;
      if (other.getTerm() != 0L) {
        setTerm(other.getTerm());
      }
      if (other.getIndex() != 0L) {
        setIndex(other.getIndex());
      }
      if (other.type_ != 0) {
        setTypeValue(other.getTypeValue());
      }
      if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
        setData(other.getData());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.bh.spider.consistent.raft.pb.Entry parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.bh.spider.consistent.raft.pb.Entry) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long term_ ;
    /**
     * <pre>
     * must be 64-bit aligned for atomic operations
     * </pre>
     *
     * <code>uint64 Term = 2;</code>
     */
    public long getTerm() {
      return term_;
    }
    /**
     * <pre>
     * must be 64-bit aligned for atomic operations
     * </pre>
     *
     * <code>uint64 Term = 2;</code>
     */
    public Builder setTerm(long value) {
      
      term_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * must be 64-bit aligned for atomic operations
     * </pre>
     *
     * <code>uint64 Term = 2;</code>
     */
    public Builder clearTerm() {
      
      term_ = 0L;
      onChanged();
      return this;
    }

    private long index_ ;
    /**
     * <pre>
     * must be 64-bit aligned for atomic operations
     * </pre>
     *
     * <code>uint64 Index = 3;</code>
     */
    public long getIndex() {
      return index_;
    }
    /**
     * <pre>
     * must be 64-bit aligned for atomic operations
     * </pre>
     *
     * <code>uint64 Index = 3;</code>
     */
    public Builder setIndex(long value) {
      
      index_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * must be 64-bit aligned for atomic operations
     * </pre>
     *
     * <code>uint64 Index = 3;</code>
     */
    public Builder clearIndex() {
      
      index_ = 0L;
      onChanged();
      return this;
    }

    private int type_ = 0;
    /**
     * <code>.com.bh.spider.consistent.raft.pb.EntryType Type = 1;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.com.bh.spider.consistent.raft.pb.EntryType Type = 1;</code>
     */
    public Builder setTypeValue(int value) {
      type_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.com.bh.spider.consistent.raft.pb.EntryType Type = 1;</code>
     */
    public com.bh.spider.consistent.raft.pb.EntryType getType() {
      @SuppressWarnings("deprecation")
      com.bh.spider.consistent.raft.pb.EntryType result = com.bh.spider.consistent.raft.pb.EntryType.valueOf(type_);
      return result == null ? com.bh.spider.consistent.raft.pb.EntryType.UNRECOGNIZED : result;
    }
    /**
     * <code>.com.bh.spider.consistent.raft.pb.EntryType Type = 1;</code>
     */
    public Builder setType(com.bh.spider.consistent.raft.pb.EntryType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      type_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.com.bh.spider.consistent.raft.pb.EntryType Type = 1;</code>
     */
    public Builder clearType() {
      
      type_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes Data = 4;</code>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }
    /**
     * <code>bytes Data = 4;</code>
     */
    public Builder setData(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      data_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes Data = 4;</code>
     */
    public Builder clearData() {
      
      data_ = getDefaultInstance().getData();
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.bh.spider.consistent.raft.pb.Entry)
  }

  // @@protoc_insertion_point(class_scope:com.bh.spider.consistent.raft.pb.Entry)
  private static final com.bh.spider.consistent.raft.pb.Entry DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.bh.spider.consistent.raft.pb.Entry();
  }

  public static com.bh.spider.consistent.raft.pb.Entry getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Entry>
      PARSER = new com.google.protobuf.AbstractParser<Entry>() {
    @java.lang.Override
    public Entry parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Entry(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Entry> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Entry> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.bh.spider.consistent.raft.pb.Entry getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

