// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: raft.proto

package com.bh.spider.consistent.raft.pb;

/**
 * Protobuf type {@code com.bh.spider.consistent.raft.pb.HardState}
 */
public  final class HardState extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.bh.spider.consistent.raft.pb.HardState)
    HardStateOrBuilder {
private static final long serialVersionUID = 0L;
  // Use HardState.newBuilder() to construct.
  private HardState(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private HardState() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private HardState(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            term_ = input.readUInt64();
            break;
          }
          case 16: {

            vote_ = input.readUInt64();
            break;
          }
          case 24: {

            commit_ = input.readUInt64();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.bh.spider.consistent.raft.pb.RaftProto.internal_static_com_bh_spider_consistent_raft_pb_HardState_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.bh.spider.consistent.raft.pb.RaftProto.internal_static_com_bh_spider_consistent_raft_pb_HardState_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.bh.spider.consistent.raft.pb.HardState.class, com.bh.spider.consistent.raft.pb.HardState.Builder.class);
  }

  public static final int TERM_FIELD_NUMBER = 1;
  private long term_;
  /**
   * <code>uint64 term = 1;</code>
   */
  public long getTerm() {
    return term_;
  }

  public static final int VOTE_FIELD_NUMBER = 2;
  private long vote_;
  /**
   * <code>uint64 vote = 2;</code>
   */
  public long getVote() {
    return vote_;
  }

  public static final int COMMIT_FIELD_NUMBER = 3;
  private long commit_;
  /**
   * <code>uint64 commit = 3;</code>
   */
  public long getCommit() {
    return commit_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (term_ != 0L) {
      output.writeUInt64(1, term_);
    }
    if (vote_ != 0L) {
      output.writeUInt64(2, vote_);
    }
    if (commit_ != 0L) {
      output.writeUInt64(3, commit_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (term_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(1, term_);
    }
    if (vote_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(2, vote_);
    }
    if (commit_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(3, commit_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.bh.spider.consistent.raft.pb.HardState)) {
      return super.equals(obj);
    }
    com.bh.spider.consistent.raft.pb.HardState other = (com.bh.spider.consistent.raft.pb.HardState) obj;

    if (getTerm()
        != other.getTerm()) return false;
    if (getVote()
        != other.getVote()) return false;
    if (getCommit()
        != other.getCommit()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TERM_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTerm());
    hash = (37 * hash) + VOTE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getVote());
    hash = (37 * hash) + COMMIT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCommit());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.bh.spider.consistent.raft.pb.HardState parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bh.spider.consistent.raft.pb.HardState parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bh.spider.consistent.raft.pb.HardState parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bh.spider.consistent.raft.pb.HardState parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bh.spider.consistent.raft.pb.HardState parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bh.spider.consistent.raft.pb.HardState parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bh.spider.consistent.raft.pb.HardState parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.bh.spider.consistent.raft.pb.HardState parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.bh.spider.consistent.raft.pb.HardState parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.bh.spider.consistent.raft.pb.HardState parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.bh.spider.consistent.raft.pb.HardState parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.bh.spider.consistent.raft.pb.HardState parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.bh.spider.consistent.raft.pb.HardState prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.bh.spider.consistent.raft.pb.HardState}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.bh.spider.consistent.raft.pb.HardState)
      com.bh.spider.consistent.raft.pb.HardStateOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bh.spider.consistent.raft.pb.RaftProto.internal_static_com_bh_spider_consistent_raft_pb_HardState_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bh.spider.consistent.raft.pb.RaftProto.internal_static_com_bh_spider_consistent_raft_pb_HardState_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bh.spider.consistent.raft.pb.HardState.class, com.bh.spider.consistent.raft.pb.HardState.Builder.class);
    }

    // Construct using com.bh.spider.consistent.raft.pb.HardState.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      term_ = 0L;

      vote_ = 0L;

      commit_ = 0L;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.bh.spider.consistent.raft.pb.RaftProto.internal_static_com_bh_spider_consistent_raft_pb_HardState_descriptor;
    }

    @java.lang.Override
    public com.bh.spider.consistent.raft.pb.HardState getDefaultInstanceForType() {
      return com.bh.spider.consistent.raft.pb.HardState.getDefaultInstance();
    }

    @java.lang.Override
    public com.bh.spider.consistent.raft.pb.HardState build() {
      com.bh.spider.consistent.raft.pb.HardState result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.bh.spider.consistent.raft.pb.HardState buildPartial() {
      com.bh.spider.consistent.raft.pb.HardState result = new com.bh.spider.consistent.raft.pb.HardState(this);
      result.term_ = term_;
      result.vote_ = vote_;
      result.commit_ = commit_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.bh.spider.consistent.raft.pb.HardState) {
        return mergeFrom((com.bh.spider.consistent.raft.pb.HardState)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.bh.spider.consistent.raft.pb.HardState other) {
      if (other == com.bh.spider.consistent.raft.pb.HardState.getDefaultInstance()) return this;
      if (other.getTerm() != 0L) {
        setTerm(other.getTerm());
      }
      if (other.getVote() != 0L) {
        setVote(other.getVote());
      }
      if (other.getCommit() != 0L) {
        setCommit(other.getCommit());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.bh.spider.consistent.raft.pb.HardState parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.bh.spider.consistent.raft.pb.HardState) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long term_ ;
    /**
     * <code>uint64 term = 1;</code>
     */
    public long getTerm() {
      return term_;
    }
    /**
     * <code>uint64 term = 1;</code>
     */
    public Builder setTerm(long value) {
      
      term_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 term = 1;</code>
     */
    public Builder clearTerm() {
      
      term_ = 0L;
      onChanged();
      return this;
    }

    private long vote_ ;
    /**
     * <code>uint64 vote = 2;</code>
     */
    public long getVote() {
      return vote_;
    }
    /**
     * <code>uint64 vote = 2;</code>
     */
    public Builder setVote(long value) {
      
      vote_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 vote = 2;</code>
     */
    public Builder clearVote() {
      
      vote_ = 0L;
      onChanged();
      return this;
    }

    private long commit_ ;
    /**
     * <code>uint64 commit = 3;</code>
     */
    public long getCommit() {
      return commit_;
    }
    /**
     * <code>uint64 commit = 3;</code>
     */
    public Builder setCommit(long value) {
      
      commit_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 commit = 3;</code>
     */
    public Builder clearCommit() {
      
      commit_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.bh.spider.consistent.raft.pb.HardState)
  }

  // @@protoc_insertion_point(class_scope:com.bh.spider.consistent.raft.pb.HardState)
  private static final com.bh.spider.consistent.raft.pb.HardState DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.bh.spider.consistent.raft.pb.HardState();
  }

  public static com.bh.spider.consistent.raft.pb.HardState getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<HardState>
      PARSER = new com.google.protobuf.AbstractParser<HardState>() {
    @java.lang.Override
    public HardState parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new HardState(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<HardState> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<HardState> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.bh.spider.consistent.raft.pb.HardState getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

