// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: raft.proto

package com.bh.spider.consistent.raft.pb;

public interface HardStateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.bh.spider.consistent.raft.pb.HardState)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 term = 1;</code>
   */
  long getTerm();

  /**
   * <code>uint64 vote = 2;</code>
   */
  long getVote();

  /**
   * <code>uint64 commit = 3;</code>
   */
  long getCommit();
}
