// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: record.proto

package com.bh.spider.consistent.raft.pb;

public interface RecordOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.bh.spider.consistent.raft.pb.Record)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 type = 1;</code>
   */
  long getType();

  /**
   * <code>uint32 crc = 2;</code>
   */
  int getCrc();

  /**
   * <code>bytes data = 3;</code>
   */
  com.google.protobuf.ByteString getData();
}
