// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: record.proto

package com.bh.spider.consistent.raft.pb;

/**
 * Protobuf type {@code com.bh.spider.consistent.raft.pb.Record}
 */
public  final class Record extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.bh.spider.consistent.raft.pb.Record)
    RecordOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Record.newBuilder() to construct.
  private Record(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Record() {
    data_ = com.google.protobuf.ByteString.EMPTY;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Record(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            type_ = input.readInt64();
            break;
          }
          case 16: {

            crc_ = input.readUInt32();
            break;
          }
          case 26: {

            data_ = input.readBytes();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.bh.spider.consistent.raft.pb.WalProto.internal_static_com_bh_spider_consistent_raft_pb_Record_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.bh.spider.consistent.raft.pb.WalProto.internal_static_com_bh_spider_consistent_raft_pb_Record_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.bh.spider.consistent.raft.pb.Record.class, com.bh.spider.consistent.raft.pb.Record.Builder.class);
  }

  public static final int TYPE_FIELD_NUMBER = 1;
  private long type_;
  /**
   * <code>int64 type = 1;</code>
   */
  public long getType() {
    return type_;
  }

  public static final int CRC_FIELD_NUMBER = 2;
  private int crc_;
  /**
   * <code>uint32 crc = 2;</code>
   */
  public int getCrc() {
    return crc_;
  }

  public static final int DATA_FIELD_NUMBER = 3;
  private com.google.protobuf.ByteString data_;
  /**
   * <code>bytes data = 3;</code>
   */
  public com.google.protobuf.ByteString getData() {
    return data_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (type_ != 0L) {
      output.writeInt64(1, type_);
    }
    if (crc_ != 0) {
      output.writeUInt32(2, crc_);
    }
    if (!data_.isEmpty()) {
      output.writeBytes(3, data_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (type_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, type_);
    }
    if (crc_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(2, crc_);
    }
    if (!data_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(3, data_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.bh.spider.consistent.raft.pb.Record)) {
      return super.equals(obj);
    }
    com.bh.spider.consistent.raft.pb.Record other = (com.bh.spider.consistent.raft.pb.Record) obj;

    if (getType()
        != other.getType()) return false;
    if (getCrc()
        != other.getCrc()) return false;
    if (!getData()
        .equals(other.getData())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getType());
    hash = (37 * hash) + CRC_FIELD_NUMBER;
    hash = (53 * hash) + getCrc();
    hash = (37 * hash) + DATA_FIELD_NUMBER;
    hash = (53 * hash) + getData().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.bh.spider.consistent.raft.pb.Record parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bh.spider.consistent.raft.pb.Record parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bh.spider.consistent.raft.pb.Record parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bh.spider.consistent.raft.pb.Record parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bh.spider.consistent.raft.pb.Record parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bh.spider.consistent.raft.pb.Record parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bh.spider.consistent.raft.pb.Record parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.bh.spider.consistent.raft.pb.Record parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.bh.spider.consistent.raft.pb.Record parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.bh.spider.consistent.raft.pb.Record parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.bh.spider.consistent.raft.pb.Record parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.bh.spider.consistent.raft.pb.Record parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.bh.spider.consistent.raft.pb.Record prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.bh.spider.consistent.raft.pb.Record}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.bh.spider.consistent.raft.pb.Record)
      com.bh.spider.consistent.raft.pb.RecordOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bh.spider.consistent.raft.pb.WalProto.internal_static_com_bh_spider_consistent_raft_pb_Record_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bh.spider.consistent.raft.pb.WalProto.internal_static_com_bh_spider_consistent_raft_pb_Record_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bh.spider.consistent.raft.pb.Record.class, com.bh.spider.consistent.raft.pb.Record.Builder.class);
    }

    // Construct using com.bh.spider.consistent.raft.pb.Record.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      type_ = 0L;

      crc_ = 0;

      data_ = com.google.protobuf.ByteString.EMPTY;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.bh.spider.consistent.raft.pb.WalProto.internal_static_com_bh_spider_consistent_raft_pb_Record_descriptor;
    }

    @java.lang.Override
    public com.bh.spider.consistent.raft.pb.Record getDefaultInstanceForType() {
      return com.bh.spider.consistent.raft.pb.Record.getDefaultInstance();
    }

    @java.lang.Override
    public com.bh.spider.consistent.raft.pb.Record build() {
      com.bh.spider.consistent.raft.pb.Record result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.bh.spider.consistent.raft.pb.Record buildPartial() {
      com.bh.spider.consistent.raft.pb.Record result = new com.bh.spider.consistent.raft.pb.Record(this);
      result.type_ = type_;
      result.crc_ = crc_;
      result.data_ = data_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.bh.spider.consistent.raft.pb.Record) {
        return mergeFrom((com.bh.spider.consistent.raft.pb.Record)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.bh.spider.consistent.raft.pb.Record other) {
      if (other == com.bh.spider.consistent.raft.pb.Record.getDefaultInstance()) return this;
      if (other.getType() != 0L) {
        setType(other.getType());
      }
      if (other.getCrc() != 0) {
        setCrc(other.getCrc());
      }
      if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
        setData(other.getData());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.bh.spider.consistent.raft.pb.Record parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.bh.spider.consistent.raft.pb.Record) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long type_ ;
    /**
     * <code>int64 type = 1;</code>
     */
    public long getType() {
      return type_;
    }
    /**
     * <code>int64 type = 1;</code>
     */
    public Builder setType(long value) {
      
      type_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 type = 1;</code>
     */
    public Builder clearType() {
      
      type_ = 0L;
      onChanged();
      return this;
    }

    private int crc_ ;
    /**
     * <code>uint32 crc = 2;</code>
     */
    public int getCrc() {
      return crc_;
    }
    /**
     * <code>uint32 crc = 2;</code>
     */
    public Builder setCrc(int value) {
      
      crc_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 crc = 2;</code>
     */
    public Builder clearCrc() {
      
      crc_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes data = 3;</code>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }
    /**
     * <code>bytes data = 3;</code>
     */
    public Builder setData(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      data_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes data = 3;</code>
     */
    public Builder clearData() {
      
      data_ = getDefaultInstance().getData();
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.bh.spider.consistent.raft.pb.Record)
  }

  // @@protoc_insertion_point(class_scope:com.bh.spider.consistent.raft.pb.Record)
  private static final com.bh.spider.consistent.raft.pb.Record DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.bh.spider.consistent.raft.pb.Record();
  }

  public static com.bh.spider.consistent.raft.pb.Record getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Record>
      PARSER = new com.google.protobuf.AbstractParser<Record>() {
    @java.lang.Override
    public Record parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Record(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Record> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Record> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.bh.spider.consistent.raft.pb.Record getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

