// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: raft.proto

package com.bh.spider.consistent.raft.pb;

public interface SnapshotMetadataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.bh.spider.consistent.raft.pb.SnapshotMetadata)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.bh.spider.consistent.raft.pb.ConfState conf_state = 1;</code>
   */
  boolean hasConfState();
  /**
   * <code>.com.bh.spider.consistent.raft.pb.ConfState conf_state = 1;</code>
   */
  com.bh.spider.consistent.raft.pb.ConfState getConfState();
  /**
   * <code>.com.bh.spider.consistent.raft.pb.ConfState conf_state = 1;</code>
   */
  com.bh.spider.consistent.raft.pb.ConfStateOrBuilder getConfStateOrBuilder();

  /**
   * <code>uint64 index = 2;</code>
   */
  long getIndex();

  /**
   * <code>uint64 term = 3;</code>
   */
  long getTerm();
}
