// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: record.proto

package com.bh.spider.consistent.raft.pb;

public final class WalProto {
  private WalProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bh_spider_consistent_raft_pb_Record_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_bh_spider_consistent_raft_pb_Record_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014record.proto\022 com.bh.spider.consistent" +
      ".raft.pb\"1\n\006Record\022\014\n\004type\030\001 \001(\003\022\013\n\003crc\030" +
      "\002 \001(\r\022\014\n\004data\030\003 \001(\014*G\n\nRecordType\022\014\n\010MET" +
      "ADATA\020\000\022\t\n\005ENTRY\020\001\022\t\n\005STATE\020\002\022\007\n\003CRC\020\003\022\014" +
      "\n\010SNAPSHOT\020\004B\014B\010WalProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_bh_spider_consistent_raft_pb_Record_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_bh_spider_consistent_raft_pb_Record_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_bh_spider_consistent_raft_pb_Record_descriptor,
        new java.lang.String[] { "Type", "Crc", "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
